CREATE TABLE category(
	category CHAR(2) PRIMARY KEY,
	category_name VARCHAR(20) NOT NULL,
	description VARCHAR(100) NOT NULL,
	rgdt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updt DATETIME DEFAULT CURRENT_TIMESTAMP
);
