CREATE TABLE students(
	student CHAR(16) PRIMARY KEY,
	mail VARCHAR(100) UNIQUE,
	name VARCHAR(20) NOT NULL,
	pw VARCHAR(100) NOT NULL,
	rgdt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updt DATETIME DEFAULT CURRENT_TIMESTAMP,
);
