CREATE TABLE subjects(
	subject CHAR(4) PRIMARY KEY,
	subject_name VARCHAR(20) NOT NULL,
	description VARCHAR(100) NOT NULL,
	status BIT DEFAULT 1,
	rgdt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updt DATETIME DEFAULT CURRENT_TIMESTAMP
);
