CREATE TABLE youtube(
	id VARCHAR(20) PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	description VARCHAR(500) NOT NULL,
	lang VARCHAR(20) NOT NULL,
	public INTEGER DEFAULT 1,
	restriction INTEGER DEFAULT 1,
	next VARCHAR(20) NULL,
	latest VARCHAR(20) NULL,
	rgdt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updt DATETIME DEFAULT CURRENT_TIMESTAMP,
);
